### ISSUE TITLE
DOMAssist needs to be a normal dependency

### ISSUE THREAD

**Issue by shelldandy** [firstandthird/toc-anchor#4]
Its a dev dependency but its needed, so its not actually working

**Comment by jgallen23** [comment]
@Antonio-Laguna

**Comment by shelldandy** [comment]
At the very least a peer-dependency so the user knows it has to install it 😛

**Comment by Antonio-Laguna** [comment]
Hey @shelldandy you're totally right! Will fix straight away

**Comment by Antonio-Laguna** [comment]
This was released as 1.0.2

**Comment by shelldandy** [comment]
Stuff happens! Specially when developing a thing or whatever we just link and test which of course that will contain even the dev dependencies as well 😛 but its different for end users.

Been there, done that!

Thanks for the fix! 🙏
